name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      # We need some Ruby installed for the environment activation tests
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"

      - name: 📦 Install dependencies
        run: yarn --frozen-lockfile

      - name: Create CHANGELOG.md
        uses: actions/github-script@v6
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            const fs = require('fs');

            const { data: releases } = await github.rest.repos.listReleases({
              owner: "Shopify",
              repo: "vscode-ruby-lsp",
            });

            const changelog = releases
              .map((release) => `# ${release.tag_name}\n${release.body}`)
              .join("\n");

            fs.writeFileSync("CHANGELOG.md", changelog);

      - run: ls
      - run: cat CHANGELOG.md
