name: Publish

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: actions/setup-node@v3
        name: Use Node.js 18.x
        with:
          node-version: "18"
          cache: "yarn"

      - name: 📦 Install dependencies
        run: yarn --frozen-lockfile

      - name: Create CHANGELOG.md
        uses: actions/github-script@v6
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            const fs = require("fs");

            const { data: releases } = await github.rest.repos.listReleases({
              owner: "Shopify",
              repo: "vscode-ruby-lsp",
            });

            console.log({context: context, github: github});

            const changelog = releases
              .filter((release) => github.event.release.prerelease || !release.prerelease)
              .map((release) => `# ${release.tag_name}\n${release.body}\n`)
              .join("\n");

            fs.writeFileSync("CHANGELOG.md", changelog);

      - run: cat CHANGELOG.md
